//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE_Template1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryDisease
    {
        public CategoryDisease()
        {
            this.MedicineDetails = new HashSet<MedicineDetail>();
        }
    
        public int C_ID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<MedicineDetail> MedicineDetails { get; set; }
    }
}
