//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE_Template1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CustomerLogin
    {
        public int ID { get; set; }
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        public string Password { get; set; }
        [Required(ErrorMessage = "The Name Required.")]
        [RegularExpression(@"^(?:.*[a-z]){4,}$", ErrorMessage = "Name  must be greater than or equal 4 characters.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "The Age Required.")]
        [RegularExpression(@"^([1-9]?[0-9])$", ErrorMessage = "Age should be 1-100.")]
        public Nullable<int> Age { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
    }

}
