//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE_Template1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MedicineDetail
    {
        public short M_ID { get; set; }
        [Required(ErrorMessage = "The ManufacturedDate Required.")]
        public System.DateTime ManufacturedDate { get; set; }
        [Required(ErrorMessage = "The ExpiredDate Required.")]
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Dosage { get; set; }
        [Required(ErrorMessage = "The Image Required.")]
        public string Image { get; set; }
        [Required(ErrorMessage = "The MedicineName Required.")]
        [RegularExpression(@"^(?:.*[a-z]){4,}$", ErrorMessage = "MedicineName  must be greater than or equal 4 characters.")]
        public string MedicineName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        [Required(ErrorMessage = "The Price Required.")]
        [RegularExpression(@"^([1-9]?[0-9]?[0-9]?[0-9])$", ErrorMessage = "Price should be 1-9999.")]
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        [Required(ErrorMessage = "The Quantity Required.")]
        [RegularExpression(@"^([1-9]?[0-9]?[0-9])$", ErrorMessage = "Quantity should be 1-999.")]
        public Nullable<int> Quantity { get; set; }
        public string AddMonth { get; set; }
        public Nullable<bool> IsDeleted { get; set; }

        public virtual CategoryDisease CategoryDisease { get; set; }
    }
}
