//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE_Template1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacySystemEntities : DbContext
    {
        public PharmacySystemEntities()
            : base("name=PharmacySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Map> Maps { get; set; }
        public DbSet<CategoryDisease> CategoryDiseases { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<MedicineDetail> MedicineDetails { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<CustomerLogin> CustomerLogins { get; set; }
        public DbSet<AdminLogin> AdminLogins { get; set; }
        public DbSet<Demo_Events> Demo_Events { get; set; }
        public DbSet<Log> Logs { get; set; }
    }
}
